"""empty message

Revision ID: f8b23eaa0964
Revises: 99203009eee2
Create Date: 2022-07-27 18:16:44.835452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b23eaa0964'
down_revision = '99203009eee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'zip',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'zip',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
